<a href="https://colab.research.google.com/github/thangakumard/PytorchSamples/blob/master/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

**LIST**

In [ ]:
my_list = [[1,2,3,4,5],[5,6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [5, 6, 7, 8, 9, 10]]

**NUMPY**

In [ ]:
np1 = np.random.rand(3,4)
np1

array([[0.97056832, 0.03331698, 0.19172309, 0.33532046],
       [0.9293703 , 0.26733617, 0.37545079, 0.97707461],
       [0.67808657, 0.45220237, 0.11287919, 0.33152443]])

**TENSOR**

In [ ]:
tensor_2d = torch.randn(3,4) # row, col
tensor_2d

tensor([[ 0.6527,  0.1875, -1.0574,  0.0434],
        [-1.2054, -1.7202,  1.3253, -0.8098],
        [ 0.1176,  0.1798,  1.0385,  0.0225]])

In [ ]:
tensor_3d = torch.zeros(3,2,3) # noOfArray, row , col
tensor_3d

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

**Tensor Ops**

In [ ]:
my_torch = torch.arange(10)
my_torch

In [ ]:
#Reshape and view
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
#Resharp if we don't know the number of items using -1
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch2 = my_torch2.reshape(5,-1) #row, col
my_torch2

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [ ]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch4 = my_torch3.reshape(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_torch3[1] = 5000
my_torch3

tensor([   0, 5000,    2,    3,    4,    5,    6,    7,    8,    9])

In [ ]:
my_torch4

tensor([[   0, 5000,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

**Tensor Math Operations**

In [ ]:
tensor_a = torch.tensor([1,2,3,4,5])
tensor_b = torch.tensor([6,7,8,9,10])

In [ ]:
#Addition
tensor_a + tensor_b

tensor([ 7,  9, 11, 13, 15])